# Generated by Django 3.2 on 2021-05-12 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
