# Generated by Django 3.2 on 2021-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
