# Generated by Django 3.2 on 2021-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_category_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
