# Generated by Django 3.2 on 2021-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
